name: Docker-Azure-Employment
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t heavenly-app-demployment .

      - name: Save Docker image as a tarball
        run: docker save heavenly-app-demployment | gzip > heavenly-app-demployment.tar.gz

      - name: Upload Docker image to Azure VM via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          source: heavenly-app-demployment.tar.gz
          target: /home/azureuser/

      - name: SSH into Azure VM and load Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          script: |
            cd /home/azureuser
            gunzip heavenly-app-demployment.tar.gz
            docker load < heavenly-app-demployment.tar
            docker rm -f heavenly-app-demployment || true
            docker run -d -p 3000:3000 --name heavenly-app-demployment heavenly-app-demployment
