name: Docker-Azure-dEmployment
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t heavenly-app-demployment .

      - name: Upload Docker image to Azure VM via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          source: .
          target: /home/azureuser/heavenly-app-demployment

      - name: SSH into Azure VM and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/docker-azure-demployment
            docker rm -f heavenly-app-demployment || true
            docker run -d -p 3000:3000 --name heavenly-app-demployment heavenly-app-demployment
